In [2]:
import numpy as np
import pandas as pd
#import matplotlib.pyplot as plt 
#from mpl_toolkits.mplot3d.axes3d import Axes3D

In [4]:
class Para:
    path_data = '20171103_20201103.xlsx'
    range_data = range(3,13)
    hold_time = range(3,13)
    percent = 0.5
para = Para()

In [18]:
number = 29
new_columns = range(number)
data_processed = pd.read_excel(para.path_data, 'Sheet1', index_col=None, na_values=['NA'],names = new_columns, header=0) #待处理数据
data_processed = data_processed.dropna(axis=0)
hrData = pd.read_excel('HR-Employee-Attrition.xlsx')

### Numpy

用python化的方式进行列表推导：

关于np.around()和int()：前者保存四舍五入值，结果的数据类型为float64. 后者只取整数部分，数据类型为int。

In [55]:
#计算出总数/section并以列表形式显示答案
#总数
section = range(6,24)
num = data_processed.shape[0]-2
num = num*np.ones(len(section))
def list_zip(section,amount): 
    result = int(min([num/a for a,num in zip(section,amount)]))
    return result
result = list_zip(section,num)
#最后得到的结果是整数

numpy中的维度称为轴(axe)，轴数和维度也称为数组的秩或维数。
从列表中创建numpy对象：

In [56]:
section = np.array(section)
section

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23])

查看对象类型： 

In [35]:
type(section)

numpy.ndarray

从内置的numpy函数中创建数组：np.zeros(length,dtype = int/float),ones,np.arrange(start = int,stop = int,step = int)
不提供arrange的step则默认为1

arrange和range：有头无尾。

另外还有np.linspace。

In [37]:
section.ndim #维数

1

索引，切片和*重构*

In [57]:
a = int(len(section)/2)
section_reshape = section.reshape(2,a)
print(section_reshape)

[[ 6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23]]


使用numpy进行模拟：
接收low，high，size参数以调整输出随机整数范围的np.random.randint()函数

关于：numpy.bincount：https://numpy.org/doc/stable/reference/generated/numpy.bincount.html

### Pandas

导入matlplotlib库：

In [59]:
import matplotlib.pyplot as plt
%matplotlib inline

Series的每个数据点均与一个索引关联。

创建Series：

In [79]:
#取行业编号
key = data_processed.iloc[1,1:].values
#取当天涨跌幅
data = data_processed.iloc[2,1:].values
#生成索引为行业编号数据为当天涨幅的新Series：
result = pd.Series(data,index = key)
result

801010.SI      1.4959
801020.SI     2.49598
801030.SI     2.98773
801040.SI     4.74229
801050.SI    0.914182
801080.SI     6.34559
801110.SI     7.09813
801120.SI      5.3385
801130.SI     1.26189
801140.SI     1.88639
801150.SI     2.84426
801160.SI     1.48315
801170.SI    0.678149
801180.SI    0.101252
801200.SI     2.05061
801210.SI     4.73094
801230.SI     3.26119
801710.SI     1.17461
801720.SI    -1.05197
801730.SI     5.33065
801740.SI     2.94796
801750.SI     3.97764
801760.SI     2.33383
801770.SI     6.70756
801780.SI   -0.381549
801790.SI     4.83573
801880.SI     3.88528
801890.SI     2.05517
dtype: object

### Pandas操作

从文件中加载或创建DataFrame的时候，首先需要检查加载后的数据（前后五行）：data.head(),tail()。

In [81]:
data_processed.tail()

0         1        2        3         4         5   \
152  2020-10-09 00:00:00   1.04712  2.51009  3.75365   1.85873   2.91338   
153  2020-10-16 00:00:00   1.76123  3.77399  3.18956   1.52863    1.0394   
154  2020-10-23 00:00:00  -5.83995 -3.89796 -2.89521  -1.08693 -0.599596   
155  2020-10-30 00:00:00  -1.47196 -3.07165 -1.16473 -0.567319  -1.41088   
156  2020-11-04 00:00:00  0.924058  3.13102  2.79362   3.36667     6.041   

          6         7          8         9   ...        19       20       21  \
152  4.20236   2.17124    2.06572   3.24089  ...   2.01047  6.15218  1.96171   
153 -1.26597   2.65205    2.54321   7.67945  ...   0.49295  1.18083  1.34443   
154  -2.5126 -0.117868  -0.457442  -4.28677  ...   -1.1985 -4.47902 -4.60096   
155  1.09085   2.39476 -0.0179926  -3.98107  ...  -1.91321  3.80522 -2.82042   
156  3.56276   8.18298    2.03093  0.993648  ...  0.883704  2.42639  2.73932   

          22        23        24        25       26       27        28  
152  3.13362   2.13524   2.20118  0.264165   1.7643  3.31802   3.25698  
153  1.15075  0.390856   1.74179   6.16451  2.99211  2.65858   2.81311  
154 -3.43804  -2.92121  -2.51041   2.18632 -1.04421  1.24759  -3.88426  
155 -3.73378   -2.4063   -3.9292  -4.04639 -5.74875  3.91123 -0.404263  
156  1.20306  0.691238  0.539869   2.73797  1.17252  5.39147   2.28789  

[5 rows x 29 columns]

向dataframe中添加新列：

In [89]:
#没什么用做样子看的
data_processed['addingColumn'] = data_processed[1]
data_processed.head()

0          1          2          3          4          5  \
1                   日期   农林牧渔(申万)     采掘(申万)     化工(申万)     钢铁(申万)   有色金属(申万)   
2                 Date  801010.SI  801020.SI  801030.SI  801040.SI  801050.SI   
3  2017-11-10 00:00:00     1.4959    2.49598    2.98773    4.74229   0.914182   
4  2017-11-17 00:00:00  -0.632207   -3.32914   -3.66471  -0.595601   -6.80515   
5  2017-11-24 00:00:00    -2.4523    1.07264   -1.40193    1.07774    2.27314   

           6          7          8          9  ...         20         21  \
1     电子(申万)   家用电器(申万)   食品饮料(申万)   纺织服装(申万)  ...   电气设备(申万)   国防军工(申万)   
2  801080.SI  801110.SI  801120.SI  801130.SI  ...  801730.SI  801740.SI   
3    6.34559    7.09813     5.3385    1.26189  ...    5.33065    2.94796   
4   -5.54601   -1.47547   -0.82588   -4.65335  ...   -5.12516   -5.42623   
5   -3.21122   -1.63727   -6.34929   -2.33598  ...    -2.5759   0.434629   

          22         23         24         25         26         27  \
1    计算机(申万)     传媒(申万)     通信(申万)     银行(申万)   非银金融(申万)     汽车(申万)   
2  801750.SI  801760.SI  801770.SI  801780.SI  801790.SI  801880.SI   
3    3.97764    2.33383    6.70756  -0.381549    4.83573    3.88528   
4    -3.9294   -5.26545   -3.41628    2.92473    1.77013   -3.86016   
5   -2.40598  -0.670392   -0.39913    3.01842   -1.16469   -2.50607   

          28 addingColumn  
1   机械设备(申万)     农林牧渔(申万)  
2  801890.SI    801010.SI  
3    2.05517       1.4959  
4   -5.32415    -0.632207  
5  -0.452213      -2.4523  

[5 rows x 30 columns]

将dataframe中的列删除：

In [90]:
del data_processed['addingColumn']
data_processed

0          1          2          3          4   \
1                     日期   农林牧渔(申万)     采掘(申万)     化工(申万)     钢铁(申万)   
2                   Date  801010.SI  801020.SI  801030.SI  801040.SI   
3    2017-11-10 00:00:00     1.4959    2.49598    2.98773    4.74229   
4    2017-11-17 00:00:00  -0.632207   -3.32914   -3.66471  -0.595601   
5    2017-11-24 00:00:00    -2.4523    1.07264   -1.40193    1.07774   
..                   ...        ...        ...        ...        ...   
152  2020-10-09 00:00:00    1.04712    2.51009    3.75365    1.85873   
153  2020-10-16 00:00:00    1.76123    3.77399    3.18956    1.52863   
154  2020-10-23 00:00:00   -5.83995   -3.89796   -2.89521   -1.08693   
155  2020-10-30 00:00:00   -1.47196   -3.07165   -1.16473  -0.567319   
156  2020-11-04 00:00:00   0.924058    3.13102    2.79362    3.36667   

            5          6          7          8          9   ...         19  \
1     有色金属(申万)     电子(申万)   家用电器(申万)   食品饮料(申万)   纺织服装(申万)  ...   建筑装饰(申万)   
2    801050.SI  801080.SI  801110.SI  801120.SI  801130.SI  ...  801720.SI   
3     0.914182    6.34559    7.09813     5.3385    1.26189  ...   -1.05197   
4     -6.80515   -5.54601   -1.47547   -0.82588   -4.65335  ...   -2.75882   
5      2.27314   -3.21122   -1.63727   -6.34929   -2.33598  ...   -1.07522   
..         ...        ...        ...        ...        ...  ...        ...   
152    2.91338    4.20236    2.17124    2.06572    3.24089  ...    2.01047   
153     1.0394   -1.26597    2.65205    2.54321    7.67945  ...    0.49295   
154  -0.599596    -2.5126  -0.117868  -0.457442   -4.28677  ...    -1.1985   
155   -1.41088    1.09085    2.39476 -0.0179926   -3.98107  ...   -1.91321   
156      6.041    3.56276    8.18298    2.03093   0.993648  ...   0.883704   

            20         21         22         23         24         25  \
1     电气设备(申万)   国防军工(申万)    计算机(申万)     传媒(申万)     通信(申万)     银行(申万)   
2    801730.SI  801740.SI  801750.SI  801760.SI  801770.SI  801780.SI   
3      5.33065    2.94796    3.97764    2.33383    6.70756  -0.381549   
4     -5.12516   -5.42623    -3.9294   -5.26545   -3.41628    2.92473   
5      -2.5759   0.434629   -2.40598  -0.670392   -0.39913    3.01842   
..         ...        ...        ...        ...        ...        ...   
152    6.15218    1.96171    3.13362    2.13524    2.20118   0.264165   
153    1.18083    1.34443    1.15075   0.390856    1.74179    6.16451   
154   -4.47902   -4.60096   -3.43804   -2.92121   -2.51041    2.18632   
155    3.80522   -2.82042   -3.73378    -2.4063    -3.9292   -4.04639   
156    2.42639    2.73932    1.20306   0.691238   0.539869    2.73797   

            26         27         28  
1     非银金融(申万)     汽车(申万)   机械设备(申万)  
2    801790.SI  801880.SI  801890.SI  
3      4.83573    3.88528    2.05517  
4      1.77013   -3.86016   -5.32415  
5     -1.16469   -2.50607  -0.452213  
..         ...        ...        ...  
152     1.7643    3.31802    3.25698  
153    2.99211    2.65858    2.81311  
154   -1.04421    1.24759   -3.88426  
155   -5.74875    3.91123  -0.404263  
156    1.17252    5.39147    2.28789  

[156 rows x 29 columns]

以及关于data.drop()：https://pandas.pydata.org/pandas-docs/version/0.21/generated/pandas.DataFrame.drop.html 

### 话说回来也可以针对某一列进行切片啊？？？

In [95]:
data_processed[1][3:5]

4   -0.632207
5     -2.4523
Name: 1, dtype: object

计算一个月（4周）的行业指数涨幅均值。

In [15]:
month = 4
data = data_processed.iloc[2:month+2,1:]
data = np.mean(data,axis = 0)
key = data_processed.iloc[0,1:].values
result = pd.Series(data.values,index = key)
result = result.sort_values(ascending = False)
#把数值都变为整数
#test = result.astype(int)
#但现在四舍入五会好一点
test = np.around(result)
#result = test.map(key)
#print(test)
#print(test,result)
result = test.value_counts(normalize = True)
print(result)

-1.0    0.535714
 0.0    0.250000
 1.0    0.107143
-2.0    0.071429
 3.0    0.035714
dtype: float64


##### 插播一个投掷硬币 正面：有饭吃 反面：没饭吃

In [110]:
test = np.random.randint(low = 0, high =2, size = 1000)
#np.bincount(test)
test = pd.Series(test)
result = test.value_counts(normalize = True)
result

0    0.501
1    0.499
dtype: float64

#### 3.3数据集：

如员工的流失率

In [31]:
attriton = 100*hrData['Attrition'].value_counts(normalize = True)['Yes']
print(attriton)

16.122448979591837


平均时薪：

In [34]:
rate = np.mean(hrData['HourlyRate'])
#hrData['HourlyRate'].mean()
rate

65.89115646258503

describe()方法可获得Series的其他描述性统计结果： 

In [38]:
print(hrData.columns)
hrData['TotalWorkingYears'].describe()

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')


count    1470.000000
mean       11.279592
std         7.780782
min         0.000000
25%         6.000000
50%        10.000000
75%        15.000000
max        40.000000
Name: TotalWorkingYears, dtype: float64